// <auto-generated />
using System;
using KPW.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KPW.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260724082727_Phase5VideoProcessingStatus")]
    partial class Phase5VideoProcessingStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KPW.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClinicianNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("PhysioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId");

                    b.HasIndex("PhysioId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentStatus = "Scheduled",
                            ClientNotes = "Follow-up on hip mobility progress.",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 3,
                            PetId = 1,
                            PhysioId = 2,
                            ScheduledDateTime = new DateTime(2026, 7, 23, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClinicId");

                    b.ToTable("Clinics", (string)null);

                    b.HasData(
                        new
                        {
                            ClinicId = 1,
                            ClinicName = "Kruger's Pet Wellness - Demo Clinic",
                            ContactNumber = "+27110000000",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PhysicalAddress = "123 Wellness Street, Pretoria, Gauteng",
                            VatNumber = "4123456789"
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.DailyTrackingLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("AppetiteScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("EnergyScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LamenessScore")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<int?>("MobilityScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("PainScore")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("LogId");

                    b.HasIndex("PetId");

                    b.ToTable("DailyTrackingLogs", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 5,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 17),
                            MobilityScore = 4,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 7,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 5,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 18),
                            MobilityScore = 5,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 6,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 6,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 19),
                            MobilityScore = 5,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 6,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 6,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 20),
                            MobilityScore = 6,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 5,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 7,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 21),
                            MobilityScore = 6,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 5,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 7,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 22),
                            MobilityScore = 7,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 4,
                            PetId = 1
                        },
                        new
                        {
                            LogId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnergyScore = 8,
                            IsActive = true,
                            IsCompleted = true,
                            LogDate = new DateOnly(2026, 7, 23),
                            MobilityScore = 7,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PainScore = 4,
                            PetId = 1
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("ClinicalPurpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommonMistakes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetSpecies")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetedMuscles")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises", (string)null);

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            ClinicalPurpose = "Improve weight-bearing tolerance after hip dysplasia diagnosis.",
                            CommonMistakes = "Allowing the dog to collapse backward instead of pushing through the hind limbs.",
                            ConditionCategory = "HipDysplasia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = 2,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SafetyNotes = "Stop if the dog shows pain, vocalises, or refuses to stand.",
                            ShortDescription = "Build hind-limb strength through controlled transitions.",
                            TargetSpecies = "Canine",
                            TargetedMuscles = "Gluteals, quadriceps, hamstrings",
                            Title = "Sit-to-Stand",
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
                        },
                        new
                        {
                            ExerciseId = 2,
                            ClinicalPurpose = "Maintain joint range before active strengthening.",
                            CommonMistakes = "Forcing the limb beyond comfortable flexion.",
                            ConditionCategory = "HipDysplasia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SafetyNotes = "Move slowly and stay within a pain-free range.",
                            ShortDescription = "Gentle hip flexion and extension to maintain joint mobility.",
                            TargetSpecies = "Canine",
                            TargetedMuscles = "Hip flexors, hip extensors",
                            Title = "Passive Range of Motion",
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
                        },
                        new
                        {
                            ExerciseId = 3,
                            ClinicalPurpose = "Improve balance and proprioception during recovery.",
                            CommonMistakes = "Moving too quickly between sides.",
                            ConditionCategory = "HipDysplasia",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = 2,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SafetyNotes = "Use a non-slip surface and support the dog if needed.",
                            ShortDescription = "Encourage controlled lateral weight transfer over the hind limbs.",
                            TargetSpecies = "Canine",
                            TargetedMuscles = "Core stabilisers, gluteals",
                            Title = "Weight Shifting",
                            VideoUrl = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.ExerciseStep", b =>
                {
                    b.Property<int>("ExerciseStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseStepId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("StepInstruction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("ExerciseStepId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseSteps", (string)null);

                    b.HasData(
                        new
                        {
                            ExerciseStepId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Position your dog on a non-slip mat with hind limbs square.",
                            StepNumber = 1
                        },
                        new
                        {
                            ExerciseStepId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Lure the dog into a controlled sit, keeping the spine neutral.",
                            StepNumber = 2
                        },
                        new
                        {
                            ExerciseStepId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Cue a slow stand using a treat, pausing briefly at the top before repeating.",
                            StepNumber = 3
                        },
                        new
                        {
                            ExerciseStepId = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 2,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Support the limb gently and flex the hip slowly for 3 seconds.",
                            StepNumber = 1
                        },
                        new
                        {
                            ExerciseStepId = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 2,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Return to neutral, then extend the hip within a comfortable range.",
                            StepNumber = 2
                        },
                        new
                        {
                            ExerciseStepId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 3,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Stand beside your dog and gently shift weight toward one hind limb.",
                            StepNumber = 1
                        },
                        new
                        {
                            ExerciseStepId = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 3,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StepInstruction = "Hold for 2 seconds, then shift to the opposite side and repeat.",
                            StepNumber = 2
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<string>("ClinicianNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("InjuryOrCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SurgeryDate")
                        .HasColumnType("date");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PetId");

                    b.ToTable("MedicalHistories", (string)null);

                    b.HasData(
                        new
                        {
                            MedicalHistoryId = 1,
                            ClinicianNotes = "Begin low-impact strengthening and proprioception work.",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Hip Dysplasia",
                            InjuryOrCondition = "Mild bilateral hip dysplasia with reduced hind-limb mobility.",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PetId = 1
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets", (string)null);

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            BirthDate = new DateOnly(2019, 5, 12),
                            Breed = "Labrador Retriever",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = 3,
                            PetName = "Buddy",
                            Species = "Canine",
                            WeightKg = 28.5m
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.RehabProgram", b =>
                {
                    b.Property<int>("RehabProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RehabProgramId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("PhysioId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RehabProgramId");

                    b.HasIndex("PetId");

                    b.HasIndex("PhysioId");

                    b.ToTable("RehabPrograms", (string)null);

                    b.HasData(
                        new
                        {
                            RehabProgramId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Low-impact introductory routine for hip dysplasia recovery.",
                            PetId = 1,
                            PhysioId = 2,
                            ProgramTitle = "Buddy Hip Recovery - Week 1",
                            StartDate = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.RehabProgramExercise", b =>
                {
                    b.Property<int>("RehabProgramExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RehabProgramExerciseId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("FrequencyPerDay")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("RehabProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.HasKey("RehabProgramExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RehabProgramId");

                    b.ToTable("RehabProgramExercises", (string)null);

                    b.HasData(
                        new
                        {
                            RehabProgramExerciseId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 1,
                            FrequencyPerDay = 2,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RehabProgramId = 1,
                            Repetitions = 8,
                            Sets = 3
                        },
                        new
                        {
                            RehabProgramExerciseId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 2,
                            FrequencyPerDay = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RehabProgramId = 1,
                            Repetitions = 10,
                            Sets = 2
                        },
                        new
                        {
                            RehabProgramExerciseId = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 3,
                            FrequencyPerDay = 1,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RehabProgramId = 1,
                            Repetitions = 6,
                            Sets = 2
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ClinicId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sysadmin@kpw.local",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$pE6t/ab4vs6xAn1qMByDZQ$GtKjB012JDKkMeTUDEMOBROTGRMOp2ubJZIZkE06NfI",
                            PhoneNumber = "+27110000001",
                            SubscriptionTier = "Pro",
                            UserRole = "SysAdmin"
                        },
                        new
                        {
                            UserId = 2,
                            ClinicId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "physio@kpw.local",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Physiotherapist",
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$pE6t/ab4vs6xAn1qMByDZQ$GtKjB012JDKkMeTUDEMOBROTGRMOp2ubJZIZkE06NfI",
                            PhoneNumber = "+27110000002",
                            SubscriptionTier = "Pro",
                            UserRole = "Physio"
                        },
                        new
                        {
                            UserId = 3,
                            ClinicId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@kpw.local",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Owner",
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$pE6t/ab4vs6xAn1qMByDZQ$GtKjB012JDKkMeTUDEMOBROTGRMOp2ubJZIZkE06NfI",
                            PhoneNumber = "+27110000003",
                            SubscriptionTier = "Free",
                            UserRole = "Owner"
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.VideoSubmission", b =>
                {
                    b.Property<int>("VideoSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoSubmissionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("PhysioFeedbackNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessedVideoStreamingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("RawVideoStorageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VideoSubmissionId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("PetId");

                    b.ToTable("VideoSubmissions", (string)null);

                    b.HasData(
                        new
                        {
                            VideoSubmissionId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExerciseId = 1,
                            IsActive = true,
                            IsReviewed = false,
                            ModifiedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PetId = 1,
                            ProcessingStatus = "Pending",
                            RawVideoStorageUrl = "videos/demo-buddy-sit-to-stand-raw.mp4"
                        });
                });

            modelBuilder.Entity("KPW.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("KPW.Domain.Entities.User", "Owner")
                        .WithMany("AppointmentsAsOwner")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPW.Domain.Entities.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPW.Domain.Entities.User", "Physio")
                        .WithMany("AppointmentsAsPhysio")
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pet");

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KPW.Domain.Entities.DailyTrackingLog", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Pet", "Pet")
                        .WithMany("DailyTrackingLogs")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("KPW.Domain.Entities.ExerciseStep", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Exercise", "Exercise")
                        .WithMany("Steps")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("KPW.Domain.Entities.MedicalHistory", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Pet", "Pet")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("KPW.Domain.Entities.Pet", b =>
                {
                    b.HasOne("KPW.Domain.Entities.User", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("KPW.Domain.Entities.RehabProgram", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Pet", "Pet")
                        .WithMany("RehabPrograms")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPW.Domain.Entities.User", "Physio")
                        .WithMany("RehabProgramsAsPhysio")
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KPW.Domain.Entities.RehabProgramExercise", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Exercise", "Exercise")
                        .WithMany("RehabProgramExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPW.Domain.Entities.RehabProgram", "RehabProgram")
                        .WithMany("RehabProgramExercises")
                        .HasForeignKey("RehabProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("RehabProgram");
                });

            modelBuilder.Entity("KPW.Domain.Entities.User", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("KPW.Domain.Entities.VideoSubmission", b =>
                {
                    b.HasOne("KPW.Domain.Entities.Exercise", "Exercise")
                        .WithMany("VideoSubmissions")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KPW.Domain.Entities.Pet", "Pet")
                        .WithMany("VideoSubmissions")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("KPW.Domain.Entities.Clinic", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KPW.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("RehabProgramExercises");

                    b.Navigation("Steps");

                    b.Navigation("VideoSubmissions");
                });

            modelBuilder.Entity("KPW.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DailyTrackingLogs");

                    b.Navigation("MedicalHistories");

                    b.Navigation("RehabPrograms");

                    b.Navigation("VideoSubmissions");
                });

            modelBuilder.Entity("KPW.Domain.Entities.RehabProgram", b =>
                {
                    b.Navigation("RehabProgramExercises");
                });

            modelBuilder.Entity("KPW.Domain.Entities.User", b =>
                {
                    b.Navigation("AppointmentsAsOwner");

                    b.Navigation("AppointmentsAsPhysio");

                    b.Navigation("Pets");

                    b.Navigation("RehabProgramsAsPhysio");
                });
#pragma warning restore 612, 618
        }
    }
}
